const STATUS = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500,
};

const ROLES = {
  ADMIN: "ADMIN",
  CONTENT_CONTRIBUTOR: "CONTENT_CONTRIBUTOR",
  REFUGEE: "REFUGEE",
};

const ACCOUNT_STATUSES = {
  ACTIVE: "ACTIVE",
  REJECTED: "REJECTED",
  PENDING: "PENDING"
};

const ORGANIZATION_TYPES = {
  NGO: "NGO",
  GOVERNMENT: "GOVERNMENT",
  PRIVATE: "PRIVATE",
  INTERNATIONAL: "INTERNATIONAL",
};

const ACCESS_LEVELS = {
  SUPER: "SUPER",
  STANDARD: "STANDARD",
};

const EDUCATION_LEVELS = {
  NONE: "NONE",
  PRIMARY: "PRIMARY",
  SECONDARY: "SECONDARY",
  HIGHER: "HIGHER",
  UNIVERSITY: "UNIVERSITY"
};

const VOTE_TARGET_TYPES = {
  POST: "Post",
  ANSWER: "Answer"
};

const VOTE_TYPES = {
  UPVOTE: "upvote",
  DOWNVOTE: "downvote"
};

export {STATUS , ROLES, ORGANIZATION_TYPES, ACCESS_LEVELS, EDUCATION_LEVELS, VOTE_TARGET_TYPES, VOTE_TYPES, ACCOUNT_STATUSES};